services:
  iredmail:
    container_name: iredmail
    image: iredmail/mariadb:stable
    ports:
      - ${PORT_HTTP:-80}:80
      - ${PORT_HTTPS:-443}:443
      - ${PORT_POP3_TLS:-110}:110
      - ${PORT_POP3_SSL:-995}:995
      - ${PORT_IMAP_TLS:-143}:143
      - ${PORT_IMAP_SSL:-993}:993
      - ${PORT_SMTP:-25}:25
      - ${PORT_SMTP_SSL:-465}:465
      - ${PORT_SMTP_TLS:-587}:587
    volumes:
      - backup-mysql:/var/vmail/backup/mysql
      - mailboxes:/var/vmail/vmail1
      - mlmmj:/var/vmail/mlmmj
      - mlmmj-archive:/var/vmail/mlmmj-archive
      - imapsieve_copy:/var/vmail/imapsieve_copy
      - custom:/opt/iredmail/custom
      - ssl:/opt/iredmail/ssl
      - mysql:/var/lib/mysql
      - clamav:/var/lib/clamav
      - sa_rules:/var/lib/spamassassin
      - postfix_queue:/var/spool/postfix
    environment:
      - HOSTNAME=${HOSTNAME}
      - FIRST_MAIL_DOMAIN=${FIRST_MAIL_DOMAIN}
      - FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=${FIRST_MAIL_DOMAIN_ADMIN_PASSWORD}
      - MLMMJADMIN_API_TOKEN=${MLMMJADMIN_API_TOKEN}
      - ROUNDCUBE_DES_KEY=${ROUNDCUBE_DES_KEY}

volumes:
  backup-mysql:
  mailboxes:
  mlmmj:
  mlmmj-archive:
  imapsieve_copy:
  custom:
  ssl:
  mysql:
  clamav:
  sa_rules:
  postfix_queue: